### PR TITLE
Update index.js

### PR DESCRIPTION
**Pull request by timthedev07**
Rephrase question to fit ts cli since it isn't a framework.

### CODE REVIEW

**Comment by divyanshu-parihar** [comment]
I think , the line says "what framework you are using" not "what framework you are making"

**Comment by timthedev07** [comment]
I'm sure typescript cli isn't a framework.🙂

**Comment by timthedev07** [comment]
So, what do you suggest?

**Comment by divyanshu-parihar** [comment]
i think Description line is fine 
but node option should be default with text Node(default)

**Comment by timthedev07** [comment]
Feel free to open another pull request.

**Comment by divyanshu-parihar** [comment]
for now i have changed the message , i will try to  make changes so node option will become default

**Comment by timthedev07** [comment]
Awesome!

**Comment by benawad** [comment]
too long of a description

**Comment by timthedev07** [comment]
Thanks.

**Pull request closed without merging**
